### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by raobilal482** [CharrafiMed/global-search-modal#82]
"I want to customize this package and don't want the results  divided into categories. Instead, I want to display all the results together in a single list. Additionally, I want to show a counter at the top indicating how many results are currently displayed."

**Comment by raobilal482** [comment]
I also want to customize view

**Comment by CharrafiMed** [comment]
hey @raobilal482 !
 Currently, the package leverages Filament's native global search under the hood. Unfortunately, we can't fetch the raw count directly from the database. Additionally, since the results are grouped by resources as per Filament's implementation, flattening them into a single list would require extra work.

At this time, these features are not supported in the package. While I could potentially add them as a workaround, I can't guarantee that it will happen soon due to some deadlines I’m currently focused on. That said, I’ve added these ideas to the roadmap for future consideration.

In the meantime, I’d encourage you to submit a PR if you’re able to implement these changes yourself. I’d be happy to review and merge it!

what do you want to customize for the view ??


Thanks for understanding! 😊

**Comment by raobilal482** [comment]
Basically I want to show result categories priority wise.

**Comment by raobilal482** [comment]
You are right, I will complete this and create a PR. However, the issue is that I don't understand how to extend the global search functionality. Could you kindly explain how you have done it?

**Comment by CharrafiMed** [comment]
what do you mean by extending the global search functionality? is how the plugin intercepts the native global search ?

**Comment by CharrafiMed** [comment]
The plugin is essentially a Livewire component., [this](https://github.com/CharrafiMed/global-search-modal/blob/master/src/Livewire/GlobalSearchModal.php) is exactly how you would build a search component in your regular Livewire components. The only difference is that it retrieves the results using the native Filament ``Filament::getGlobalSearchProvider()->getResults($search)``

**Comment by raobilal482** [comment]
> what do you mean by extending the global search functionality? is how the plugin intercepts the native global search ?

Yes

**Comment by raobilal482** [comment]
I create a separate livewire component for global search. And write custom logic for global search there. But when i search something it is still showing native result. I mean how the search goes to my component instead of native global search.

**Comment by CharrafiMed** [comment]
## General Idea Behind the Plugin

The general idea behind the plugin is to listen for a click event on a native global search input and then open the search modal. You can find how, in the [observer.js](https://github.com/CharrafiMed/global-search-modal/blob/master/resources/js/observer.js) file.

**Note:** You will need to register the necessary scripts in the service provider to ensure proper integration.

Once the modal is triggered, you can use the input to collect the search query and perform the search with it. 

However, creating a fully functional search component goes beyond this basic implementation. You'll need more configuration and setup to handle various edge cases and enhance the overall functionality, which is too detailed to explain here. 

**Go ahead and fork the package into your Laravel project and play with it** to understand the full functionality and see how it fits into your setup.

then you can even create a global search  component  that feet you needs without any dependencies 

*I can't explain more beyond this point.*
